[project]
name = "base"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "imgaug>=0.4.0",
    "ipykernel>=6.31.0",
    "matplotlib>=3.9.4",
    "numpy==1.26.4",
    "scikit-learn>=1.6.1",
    "tensorflow[and-cuda]>=2.20.0",
]
